export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAIL = "CREATE_ADDRESS_FAIL";
export const CREATE_ADDRESS_RESET = "CREATE_ADDRESS_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_ADDRESS_REQUEST = "ALL_ADDRESS_REQUEST";
export const ALL_ADDRESS_SUCCESS = "ALL_ADDRESS_SUCCESS";
export const ALL_ADDRESS_FAIL = "ALL_ADDRESS_FAIL";
export const ALL_ADDRESS_RESET = "ALL_ADDRESS_RESET";

export const SINGLE_ADDRESS_REQUEST = "SINGLE_ADDRESS_REQUEST";
export const SINGLE_ADDRESS_SUCCESS = "SINGLE_ADDRESS_SUCCESS";
export const SINGLE_ADDRESS_FAIL = "SINGLE_ADDRESS_FAIL";
export const SINGLE_ADDRESS_RESET = "SINGLE_ADDRESS_RESET";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const SET_ADDRESS_REQUEST = "SET_ADDRESS_REQUEST";
export const SET_ADDRESS_SUCCESS = "SET_ADDRESS_SUCCESS";
export const SET_ADDRESS_RESET = "SET_ADDRESS_RESET";
export const SET_ADDRESS_FAIL = "SET_ADDRESS_FAIL";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";
export const DELETE_ADDRESS_RESET = "DELETE_ADDRESS_RESET";
