export const ALL_STORE_SALES_REQUEST = "ALL_STORE_SALES_REQUEST";
export const ALL_STORE_SALES_SUCCESS = "ALL_STORE_SALES_SUCCESS";
export const ALL_STORE_SALES_FAIL = "ALL_STORE_SALES_FAIL";

export const SINGLE_STORE_BRANCH_REQUEST = "SINGLE_STORE_BRANCH_REQUEST";
export const SINGLE_STORE_BRANCH_SUCCESS = "SINGLE_STORE_BRANCH_SUCCESS";
export const SINGLE_STORE_BRANCH_FAIL = "SINGLE_STORE_BRANCH_FAIL";

export const ALL_STAFF_REQUEST = "ALL_STAFF_REQUEST";
export const ALL_STAFF_SUCCESS = "ALL_STAFF_SUCCESS";
export const ALL_STAFF_FAIL = "ALL_STAFF_FAIL";

export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";

export const SALES_WALKIN_REQUEST = "SALES_WALKIN_REQUEST";
export const SALES_WALKIN_SUCCESS = "SALES_WALKIN_SUCCESS";
export const SALES_WALKIN_FAIL = "SALES_WALKIN_FAIL";

export const SALES_ORDER_REQUEST = "SALES_ORDER_REQUEST";
export const SALES_ORDER_SUCCESS = "SALES_ORDER_SUCCESS";
export const SALES_ORDER_FAIL = "SALES_ORDER_FAIL";

export const ALL_ORDER_TRANSACTIONS_REQUEST = "ALL_ORDER_TRANSACTIONS_REQUEST";
export const ALL_ORDER_TRANSACTIONS_SUCCESS = "ALL_ORDER_TRANSACTIONS_SUCCESS";
export const ALL_ORDER_TRANSACTIONS_FAIL = "ALL_ORDER_TRANSACTIONS_FAIL";

export const ALL_ORDER_GALLON_TYPE_REQUEST = "ALL_ORDER_GALLON_TYPE_REQUEST";
export const ALL_ORDER_GALLON_TYPE_SUCCESS = "ALL_ORDER_GALLON_TYPE_SUCCESS";
export const ALL_ORDER_GALLON_TYPE_FAIL = "ALL_ORDER_GALLON_TYPE_FAIL";

export const ALL_ORDER_BARANGAY_REQUEST = "ALL_ORDER_BARANGAY_REQUEST";
export const ALL_ORDER_BARANGAY_SUCCESS = "ALL_ORDER_BARANGAY_SUCCESS";
export const ALL_ORDER_BARANGAY_FAIL = "ALL_ORDER_BARANGAY_FAIL";

export const STAFF_PERFORMANCE_REQUEST = "STAFF_PERFORMANCE_REQUEST";
export const STAFF_PERFORMANCE_SUCCESS = "STAFF_PERFORMANCE_SUCCESS";
export const STAFF_PERFORMANCE_FAIL = "STAFF_PERFORMANCE_FAIL";

export const CURRENT_STORE_SALES_REQUEST = "CURRENT_STORE_SALES_REQUEST";
export const CURRENT_STORE_SALES_SUCCESS = "CURRENT_STORE_SALES_SUCCESS";
export const CURRENT_STORE_SALES_FAIL = "CURRENT_STORE_SALES_FAIL";

export const EMPLOYEE_BRANCH_REQUEST = "EMPLOYEE_BRANCH_REQUEST";
export const EMPLOYEE_BRANCH_SUCCESS = "EMPLOYEE_BRANCH_SUCCESS";
export const EMPLOYEE_BRANCH_FAIL = "EMPLOYEE_BRANCH_FAIL";

export const EMPLOYEE_ORDER_SALES_REQUEST = "EMPLOYEE_ORDER_SALES_REQUEST";
export const EMPLOYEE_ORDER_SALES_SUCCESS = "EMPLOYEE_ORDER_SALES_SUCCESS";
export const EMPLOYEE_ORDER_SALES_FAIL = "EMPLOYEE_ORDER_SALES_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const GET_SINGLE_REVIEW_REQUEST = "GET_SINGLE_REVIEW_REQUEST";
export const GET_SINGLE_REVIEW_SUCCESS = "GET_SINGLE_REVIEW_SUCCESS";
export const GET_SINGLE_REVIEW_FAIL = "GET_SINGLE_REVIEW_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";