export const ALL_STORE_SALES_REQUEST = "ALL_STORE_SALES_REQUEST";
export const ALL_STORE_SALES_SUCCESS = "ALL_STORE_SALES_SUCCESS";
export const ALL_STORE_SALES_FAIL = "ALL_STORE_SALES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";