export const ALL_STORE_SALES_REQUEST = "ALL_STORE_SALES_REQUEST";
export const ALL_STORE_SALES_SUCCESS = "ALL_STORE_SALES_SUCCESS";
export const ALL_STORE_SALES_FAIL = "ALL_STORE_SALES_FAIL";

export const SINGLE_STORE_BRANCH_REQUEST = "SINGLE_STORE_BRANCH_REQUEST";
export const SINGLE_STORE_BRANCH_SUCCESS = "SINGLE_STORE_BRANCH_SUCCESS";
export const SINGLE_STORE_BRANCH_FAIL = "SINGLE_STORE_BRANCH_FAIL";

export const ALL_STAFF_REQUEST = "ALL_STAFF_REQUEST";
export const ALL_STAFF_SUCCESS = "ALL_STAFF_SUCCESS";
export const ALL_STAFF_FAIL = "ALL_STAFF_FAIL";

export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";

export const SALES_WALKIN_REQUEST = "SALES_WALKIN_REQUEST";
export const SALES_WALKIN_SUCCESS = "SALES_WALKIN_SUCCESS";
export const SALES_WALKIN_FAIL = "SALES_WALKIN_FAIL";

export const ALL_ORDER_TRANSACTIONS_REQUEST = "ALL_ORDER_TRANSACTIONS_REQUEST";
export const ALL_ORDER_TRANSACTIONS_SUCCESS = "ALL_ORDER_TRANSACTIONS_SUCCESS";
export const ALL_ORDER_TRANSACTIONS_FAIL = "ALL_ORDER_TRANSACTIONS_FAIL";

export const ALL_ORDER_GALLON_TYPE_REQUEST = "ALL_ORDER_GALLON_TYPE_REQUEST";
export const ALL_ORDER_GALLON_TYPE_SUCCESS = "ALL_ORDER_GALLON_TYPE_SUCCESS";
export const ALL_ORDER_GALLON_TYPE_FAIL = "ALL_ORDER_GALLON_TYPE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";