export const CREATE_BARANGAYHEALTH_REQUEST = "CREATE_BARANGAYHEALTH_REQUEST";
export const CREATE_BARANGAYHEALTH_SUCCESS = "CREATE_BARANGAYHEALTH_SUCCESS";
export const CREATE_BARANGAYHEALTH_FAIL = "CREATE_BARANGAYHEALTH_FAIL";
export const CREATE_BARANGAYHEALTH_RESET = "CREATE_BARANGAYHEALTH_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_BARANGAYHEALTH_REQUEST = "ALL_BARANGAYHEALTH_REQUEST";
export const ALL_BARANGAYHEALTH_SUCCESS = "ALL_BARANGAYHEALTH_SUCCESS";
export const ALL_BARANGAYHEALTH_FAIL = "ALL_BARANGAYHEALTH_FAIL";
export const ALL_BARANGAYHEALTH_RESET = "ALL_BARANGAYHEALTH_RESET";

export const SINGLE_BARANGAYHEALTH_REQUEST = "SINGLE_BARANGAYHEALTH_REQUEST";
export const SINGLE_BARANGAYHEALTH_SUCCESS = "SINGLE_BARANGAYHEALTH_SUCCESS";
export const SINGLE_BARANGAYHEALTH_FAIL = "SINGLE_BARANGAYHEALTH_FAIL";
export const SINGLE_BARANGAYHEALTH_RESET = "SINGLE_BARANGAYHEALTH_RESET";

export const UPDATE_BARANGAYHEALTH_REQUEST = "UPDATE_BARANGAYHEALTH_REQUEST";
export const UPDATE_BARANGAYHEALTH_SUCCESS = "UPDATE_BARANGAYHEALTH_SUCCESS";
export const UPDATE_BARANGAYHEALTH_RESET = "UPDATE_BARANGAYHEALTH_RESET";
export const UPDATE_BARANGAYHEALTH_FAIL = "UPDATE_BARANGAYHEALTH_FAIL";

export const DELETE_BARANGAYHEALTH_REQUEST = "DELETE_BARANGAYHEALTH_REQUEST";
export const DELETE_BARANGAYHEALTH_SUCCESS = "DELETE_BARANGAYHEALTH_SUCCESS";
export const DELETE_BARANGAYHEALTH_FAIL = "DELETE_BARANGAYHEALTH_FAIL";
export const DELETE_BARANGAYHEALTH_RESET = "DELETE_BARANGAYHEALTH_RESET";
