export const CREATE_BARANGAYHEALTH_REQUEST = "CREATE_BARANGAYHEALTH_REQUEST";
export const CREATE_BARANGAYHEALTH_SUCCESS = "CREATE_BARANGAYHEALTH_SUCCESS";
export const CREATE_BARANGAYHEALTH_FAIL = "CREATE_BARANGAYHEALTH_FAIL";
export const CREATE_BARANGAYHEALTH_RESET = "CREATE_BARANGAYHEALTH_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
