export const CREATE_BUSINESSPERMIT_REQUEST = "CREATE_BUSINESSPERMIT_REQUEST";
export const CREATE_BUSINESSPERMIT_SUCCESS = "CREATE_BUSINESSPERMIT_SUCCESS";
export const CREATE_BUSINESSPERMIT_FAIL = "CREATE_BUSINESSPERMIT_FAIL";
export const CREATE_BUSINESSPERMIT_RESET = "CREATE_BUSINESSPERMIT_RESET";

export const ALL_BUSINESSPERMIT_REQUEST = "ALL_BUSINESSPERMIT_REQUEST";
export const ALL_BUSINESSPERMIT_SUCCESS = "ALL_BUSINESSPERMIT_SUCCESS";
export const ALL_BUSINESSPERMIT_FAIL = "ALL_BUSINESSPERMIT_FAIL";
export const ALL_BUSINESSPERMIT_RESET = "ALL_BUSINESSPERMIT_RESET";

export const SINGLE_BUSINESSPERMIT_REQUEST = "SINGLE_BUSINESSPERMIT_REQUEST";
export const SINGLE_BUSINESSPERMIT_SUCCESS = "SINGLE_BUSINESSPERMIT_SUCCESS";
export const SINGLE_BUSINESSPERMIT_FAIL = "SINGLE_BUSINESSPERMIT_FAIL";
export const SINGLE_BUSINESSPERMIT_RESET = "SINGLE_BUSINESSPERMIT_RESET";

export const UPDATE_BUSINESSPERMIT_REQUEST = "UPDATE_BUSINESSPERMIT_REQUEST";
export const UPDATE_BUSINESSPERMIT_SUCCESS = "UPDATE_BUSINESSPERMIT_SUCCESS";
export const UPDATE_BUSINESSPERMIT_RESET = "UPDATE_BUSINESSPERMIT_RESET";
export const UPDATE_BUSINESSPERMIT_FAIL = "UPDATE_BUSINESSPERMIT_FAIL";

export const DELETE_BUSINESSPERMIT_REQUEST = "DELETE_BUSINESSPERMIT_REQUEST";
export const DELETE_BUSINESSPERMIT_SUCCESS = "DELETE_BUSINESSPERMIT_SUCCESS";
export const DELETE_BUSINESSPERMIT_FAIL = "DELETE_BUSINESSPERMIT_FAIL";
export const DELETE_BUSINESSPERMIT_RESET = "DELETE_BUSINESSPERMIT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
