export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const SAVE_STOREBRANCH_INFO = "SAVE_STOREBRANCH_INFO";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_CART_PRODUCT = "ADD_TO_CART_PRODUCT";
export const REMOVE_ITEM_CART_PRODUCT = "REMOVE_ITEM_CART_PRODUCT";
