export const CREATE_GALLON_REQUEST = "CREATE_GALLON_REQUEST";
export const CREATE_GALLON_SUCCESS = "CREATE_GALLON_SUCCESS";
export const CREATE_GALLON_FAIL = "CREATE_GALLON_FAIL";
export const CREATE_GALLON_RESET = "CREATE_GALLON_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MY_GALLON_REQUEST = "MY_GALLON_REQUEST";
export const MY_GALLON_SUCCESS = "MY_GALLON_SUCCESS";
export const MY_GALLON_FAIL = "MY_GALLON_FAIL";

export const GALLON_DETAILS_REQUEST = "GALLON_DETAILS_REQUEST";
export const GALLON_DETAILS_SUCCESS = "GALLON_DETAILS_SUCCESS";
export const GALLON_DETAILS_FAIL = "GALLON_DETAILS_FAIL";

export const UPDATE_GALLON_REQUEST = "UPDATE_GALLON_REQUEST";
export const UPDATE_GALLON_SUCCESS = "UPDATE_GALLON_SUCCESS";
export const UPDATE_GALLON_RESET = "UPDATE_GALLON_RESET";
export const UPDATE_GALLON_FAIL = "UPDATE_GALLON_FAIL";

export const DELETE_GALLON_REQUEST = "DELETE_GALLON_REQUEST";
export const DELETE_GALLON_SUCCESS = "DELETE_GALLON_SUCCESS";
export const DELETE_GALLON_RESET = "DELETE_GALLON_RESET";
export const DELETE_GALLON_FAIL = "DELETE_GALLON_FAIL";

export const ALL_GALLONS_REQUEST = "ALL_GALLONS_REQUEST";
export const ALL_GALLONS_SUCCESS = "ALL_GALLONS_SUCCESS";
export const ALL_GALLONS_FAIL = "ALL_GALLONS_FAIL";

