export const CREATE_MACHINECLEANING_REQUEST = "CREATE_MACHINECLEANING_REQUEST";
export const CREATE_MACHINECLEANING_SUCCESS = "CREATE_MACHINECLEANING_SUCCESS";
export const CREATE_MACHINECLEANING_FAIL = "CREATE_MACHINECLEANING_FAIL";
export const CREATE_MACHINECLEANING_RESET = "CREATE_MACHINECLEANING_RESET";

export const ALL_MACHINECLEANING_REQUEST = "ALL_MACHINECLEANING_REQUEST";
export const ALL_MACHINECLEANING_SUCCESS = "ALL_MACHINECLEANING_SUCCESS";
export const ALL_MACHINECLEANING_FAIL = "ALL_MACHINECLEANING_FAIL";
export const ALL_MACHINECLEANING_RESET = "ALL_MACHINECLEANING_RESET";

export const SINGLE_MACHINECLEANING_REQUEST = "SINGLE_MACHINECLEANING_REQUEST";
export const SINGLE_MACHINECLEANING_SUCCESS = "SINGLE_MACHINECLEANING_SUCCESS";
export const SINGLE_MACHINECLEANING_FAIL = "SINGLE_MACHINECLEANING_FAIL";
export const SINGLE_MACHINECLEANING_RESET = "SINGLE_MACHINECLEANING_RESET";

export const UPDATE_MACHINECLEANING_REQUEST = "UPDATE_MACHINECLEANING_REQUEST";
export const UPDATE_MACHINECLEANING_SUCCESS = "UPDATE_MACHINECLEANING_SUCCESS";
export const UPDATE_MACHINECLEANING_RESET = "UPDATE_MACHINECLEANING_RESET";
export const UPDATE_MACHINECLEANING_FAIL = "UPDATE_MACHINECLEANING_FAIL";

export const DELETE_MACHINECLEANING_REQUEST = "DELETE_MACHINECLEANING_REQUEST";
export const DELETE_MACHINECLEANING_SUCCESS = "DELETE_MACHINECLEANING_SUCCESS";
export const DELETE_MACHINECLEANING_FAIL = "DELETE_MACHINECLEANING_FAIL";
export const DELETE_MACHINECLEANING_RESET = "DELETE_MACHINECLEANING_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
