export const CREATE_PHYSICALCHEMTEST_REQUEST = "CREATE_PHYSICALCHEMTEST_REQUEST";
export const CREATE_PHYSICALCHEMTEST_SUCCESS = "CREATE_PHYSICALCHEMTEST_SUCCESS";
export const CREATE_PHYSICALCHEMTEST_FAIL = "CREATE_PHYSICALCHEMTEST_FAIL";
export const CREATE_PHYSICALCHEMTEST_RESET = "CREATE_PHYSICALCHEMTEST_RESET";

export const ALL_PHYSICALCHEMTEST_REQUEST = "ALL_PHYSICALCHEMTEST_REQUEST";
export const ALL_PHYSICALCHEMTEST_SUCCESS = "ALL_PHYSICALCHEMTEST_SUCCESS";
export const ALL_PHYSICALCHEMTEST_FAIL = "ALL_PHYSICALCHEMTEST_FAIL";
export const ALL_PHYSICALCHEMTEST_RESET = "ALL_PHYSICALCHEMTEST_RESET";

export const SINGLE_PHYSICALCHEMTEST_REQUEST = "SINGLE_PHYSICALCHEMTEST_REQUEST";
export const SINGLE_PHYSICALCHEMTEST_SUCCESS = "SINGLE_PHYSICALCHEMTEST_SUCCESS";
export const SINGLE_PHYSICALCHEMTEST_FAIL = "SINGLE_PHYSICALCHEMTEST_FAIL";
export const SINGLE_PHYSICALCHEMTEST_RESET = "SINGLE_PHYSICALCHEMTEST_RESET";

export const UPDATE_PHYSICALCHEMTEST_REQUEST = "UPDATE_PHYSICALCHEMTEST_REQUEST";
export const UPDATE_PHYSICALCHEMTEST_SUCCESS = "UPDATE_PHYSICALCHEMTEST_SUCCESS";
export const UPDATE_PHYSICALCHEMTEST_RESET = "UPDATE_PHYSICALCHEMTEST_RESET";
export const UPDATE_PHYSICALCHEMTEST_FAIL = "UPDATE_PHYSICALCHEMTEST_FAIL";

export const DELETE_PHYSICALCHEMTEST_REQUEST = "DELETE_PHYSICALCHEMTEST_REQUEST";
export const DELETE_PHYSICALCHEMTEST_SUCCESS = "DELETE_PHYSICALCHEMTEST_SUCCESS";
export const DELETE_PHYSICALCHEMTEST_FAIL = "DELETE_PHYSICALCHEMTEST_FAIL";
export const DELETE_PHYSICALCHEMTEST_RESET = "DELETE_PHYSICALCHEMTEST_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
