export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_PRODUCTSTOCKLOG_REQUEST = "ALL_PRODUCTSTOCKLOG_REQUEST";
export const ALL_PRODUCTSTOCKLOG_SUCCESS = "ALL_PRODUCTSTOCKLOG_SUCCESS";
export const ALL_PRODUCTSTOCKLOG_FAIL = "ALL_PRODUCTSTOCKLOG_FAIL";

export const UPDATE_PRODUCTSTOCKLOG_REQUEST = "UPDATE_PRODUCTSTOCKLOG_REQUEST";
export const UPDATE_PRODUCTSTOCKLOG_SUCCESS = "UPDATE_PRODUCTSTOCKLOG_SUCCESS";
export const UPDATE_PRODUCTSTOCKLOG_FAIL = "UPDATE_PRODUCTSTOCKLOG_FAIL";
export const UPDATE_PRODUCTSTOCKLOG_RESET = "UPDATE_PRODUCTSTOCKLOG_RESET";

export const DELETE_PRODUCTSTOCKLOG_REQUEST = "DELETE_PRODUCTSTOCKLOG_REQUEST";
export const DELETE_PRODUCTSTOCKLOG_SUCCESS = "DELETE_PRODUCTSTOCKLOG_SUCCESS";
export const DELETE_PRODUCTSTOCKLOG_FAIL = "DELETE_PRODUCTSTOCKLOG_FAIL";
export const DELETE_PRODUCTSTOCKLOG_RESET = "DELETE_PRODUCTSTOCKLOG_RESET";

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";
export const SINGLE_PRODUCT_RESET = "SINGLE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
