export const CREATE_STOREBRANCH_REQUEST = "CREATE_STOREBRANCH_REQUEST";
export const CREATE_STOREBRANCH_SUCCESS = "CREATE_STOREBRANCH_SUCCESS";
export const CREATE_STOREBRANCH_FAIL = "CREATE_STOREBRANCH_FAIL";
export const CREATE_STOREBRANCH_RESET = "CREATE_STOREBRANCH_RESET";

export const ALL_STOREBRANCH_REQUEST = "ALL_STOREBRANCH_REQUEST";
export const ALL_STOREBRANCH_SUCCESS = "ALL_GALLONS_SUCCESS";
export const ALL_STOREBRANCH_FAIL = "ALL_STOREBRANCH_FAIL";

export const DELETE_STOREBRANCH_REQUEST = "DELETE_STOREBRANCH_REQUEST";
export const DELETE_STOREBRANCH_SUCCESS = "DELETE_STOREBRANCH_SUCCESS";
export const DELETE_STOREBRANCH_RESET = "DELETE_STOREBRANCH_RESET";
export const DELETE_STOREBRANCH_FAIL = "DELETE_STOREBRANCH_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
