export const CREATE_STOREBARANGAY_REQUEST = "CREATE_STOREBARANGAY_REQUEST";
export const CREATE_STOREBARANGAY_SUCCESS = "CREATE_STOREBARANGAY_SUCCESS";
export const CREATE_STOREBARANGAY_FAIL = "CREATE_STOREBARANGAY_FAIL";
export const CREATE_STOREBARANGAY_RESET = "CREATE_STOREBARANGAY_RESET";

export const ALL_STOREBARANGAY_REQUEST = "ALL_STOREBARANGAY_REQUEST";
export const ALL_STOREBARANGAY_SUCCESS = "ALL_STOREBARANGAY_SUCCESS";
export const ALL_STOREBARANGAY_FAIL = "ALL_STOREBARANGAY_FAIL";
export const ALL_STOREBARANGAY_RESET = "ALL_STOREBARANGAY_RESET";

export const SINGLE_STOREBARANGAY_REQUEST = "SINGLE_STOREBARANGAY_REQUEST";
export const SINGLE_STOREBARANGAY_SUCCESS = "SINGLE_STOREBARANGAY_SUCCESS";
export const SINGLE_STOREBARANGAY_FAIL = "SINGLE_STOREBARANGAY_FAIL";
export const SINGLE_STOREBARANGAY_RESET = "SINGLE_STOREBARANGAY_RESET";

export const UPDATE_STOREBARANGAY_REQUEST = "UPDATE_STOREBARANGAY_REQUEST";
export const UPDATE_STOREBARANGAY_SUCCESS = "UPDATE_STOREBARANGAY_SUCCESS";
export const UPDATE_STOREBARANGAY_RESET = "UPDATE_STOREBARANGAY_RESET";
export const UPDATE_STOREBARANGAY_FAIL = "UPDATE_STOREBARANGAY_FAIL";

export const DELETE_STOREBARANGAY_REQUEST = "DELETE_STOREBARANGAY_REQUEST";
export const DELETE_STOREBARANGAY_SUCCESS = "DELETE_STOREBARANGAY_SUCCESS";
export const DELETE_STOREBARANGAY_FAIL = "DELETE_STOREBARANGAY_FAIL";
export const DELETE_STOREBARANGAY_RESET = "DELETE_STOREBARANGAY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
