export const CREATE_STORESTAFF_REQUEST = "CREATE_STORESTAFF_REQUEST";
export const CREATE_STORESTAFF_SUCCESS = "CREATE_STORESTAFF_SUCCESS";
export const CREATE_STORESTAFF_FAIL = "CREATE_STORESTAFF_FAIL";
export const CREATE_STORESTAFF_RESET = "CREATE_STORESTAFF_RESET";

export const ALL_STORESTAFF_REQUEST = "ALL_STORESTAFF_REQUEST";
export const ALL_STORESTAFF_SUCCESS = "ALL_STORESTAFF_SUCCESS";
export const ALL_STORESTAFF_FAIL = "ALL_STORESTAFF_FAIL";
export const ALL_STORESTAFF_RESET = "ALL_STORESTAFF_RESET";

export const SINGLE_STORESTAFF_REQUEST = "SINGLE_STORESTAFF_REQUEST";
export const SINGLE_STORESTAFF_SUCCESS = "SINGLE_STORESTAFF_SUCCESS";
export const SINGLE_STORESTAFF_FAIL = "SINGLE_STORESTAFF_FAIL";
export const SINGLE_STORESTAFF_RESET = "SINGLE_STORESTAFF_RESET";

export const DELETE_STORESTAFF_REQUEST = "DELETE_STORESTAFF_REQUEST";
export const DELETE_STORESTAFF_SUCCESS = "DELETE_STORESTAFF_SUCCESS";
export const DELETE_STORESTAFF_FAIL = "DELETE_STORESTAFF_FAIL";
export const DELETE_STORESTAFF_RESET = "DELETE_STORESTAFF_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
