export const ALL_SUPERADMIN_USERS_REQUEST = "ALL_SUPERADMIN_USERS_REQUEST";
export const ALL_SUPERADMIN_USERS_SUCCESS = "ALL_SUPERADMIN_USERS_SUCCESS";
export const ALL_SUPERADMIN_USERS_FAIL = "ALL_SUPERADMIN_USERS_FAIL";
export const ALL_SUPERADMIN_USERS_RESET = "ALL_SUPERADMIN_USERS_RESET";

export const ALL_SUPERADMIN_PENDINGADMIN_REQUEST = "ALL_SUPERADMIN_PENDINGADMIN_REQUEST";
export const ALL_SUPERADMIN_PENDINGADMIN_SUCCESS = "ALL_SUPERADMIN_PENDINGADMIN_SUCCESS";
export const ALL_SUPERADMIN_PENDINGADMIN_FAIL = "ALL_SUPERADMIN_PENDINGADMIN_FAIL";
export const ALL_SUPERADMIN_PENDINGADMIN_RESET = "ALL_SUPERADMIN_PENDINGADMIN_RESET";

export const ALL_SUPERADMIN_ADMIN_REQUEST = "ALL_SUPERADMIN_ADMIN_REQUEST";
export const ALL_SUPERADMIN_ADMIN_SUCCESS = "ALL_SUPERADMIN_ADMIN_SUCCESS";
export const ALL_SUPERADMIN_ADMIN_FAIL = "ALL_SUPERADMIN_ADMIN_FAIL";
export const ALL_SUPERADMIN_ADMIN_RESET = "ALL_SUPERADMIN_ADMIN_RESET";

export const ALL_SUPERADMIN_ADMINSTOREBRANCH_REQUEST = "ALL_SUPERADMIN_ADMINSTOREBRANCH_REQUEST";
export const ALL_SUPERADMIN_ADMINSTOREBRANCH_SUCCESS = "ALL_SUPERADMIN_ADMINSTOREBRANCH_SUCCESS";
export const ALL_SUPERADMIN_ADMINSTOREBRANCH_FAIL = "ALL_SUPERADMIN_ADMINSTOREBRANCH_FAIL";
export const ALL_SUPERADMIN_ADMINSTOREBRANCH_RESET = "ALL_SUPERADMIN_ADMINSTOREBRANCH_RESET";

export const ALL_SUPERADMIN_ADMINAPPROVAL_REQUEST = "ALL_SUPERADMIN_ADMINAPPROVAL_REQUEST";
export const ALL_SUPERADMIN_ADMINAPPROVAL_SUCCESS = "ALL_SUPERADMIN_ADMINAPPROVAL_SUCCESS";
export const ALL_SUPERADMIN_ADMINAPPROVAL_FAIL = "ALL_SUPERADMIN_ADMINAPPROVAL_FAIL";
export const ALL_SUPERADMIN_ADMINAPPROVAL_RESET = "ALL_SUPERADMIN_ADMINAPPROVAL_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
