export const CREATE_TYPESGALLON_REQUEST = "CREATE_TYPESGALLON_REQUEST";
export const CREATE_TYPESGALLON_SUCCESS = "CREATE_TYPESGALLON_SUCCESS";
export const CREATE_TYPESGALLON_FAIL = "CREATE_TYPESGALLON_FAIL";
export const CREATE_TYPESGALLON_RESET = "CREATE_TYPESGALLON_RESET";

export const ALL_TYPESGALLON_REQUEST = "ALL_TYPESGALLON_REQUEST";
export const ALL_TYPESGALLON_SUCCESS = "ALL_TYPESGALLON_SUCCESS";
export const ALL_TYPESGALLON_FAIL = "ALL_TYPESGALLON_FAIL";

export const DELETE_TYPESGALLON_REQUEST = "DELETE_TYPESGALLON_REQUEST";
export const DELETE_TYPESGALLON_SUCCESS = "DELETE_TYPESGALLON_SUCCESS";
export const DELETE_TYPESGALLON_RESET = "DELETE_TYPESGALLON_RESET";
export const DELETE_TYPESGALLON_FAIL = "DELETE_TYPESGALLON_FAIL";

export const SINGLE_TYPESGALLON_REQUEST = "SINGLE_TYPESGALLON_REQUEST";
export const SINGLE_TYPESGALLON_SUCCESS = "SINGLE_TYPESGALLON_SUCCESS";
export const SINGLE_TYPESGALLON_FAIL = "SINGLE_TYPESGALLON_FAIL";
export const SINGLE_TYPESGALLON_RESET = "SINGLE_TYPESGALLON_RESET";

export const UPDATE_TYPESGALLON_REQUEST = "UPDATE_TYPESGALLON_REQUEST";
export const UPDATE_TYPESGALLON_SUCCESS = "UPDATE_TYPESGALLON_SUCCESS";
export const UPDATE_TYPESGALLON_RESET = "UPDATE_TYPESGALLON_RESET";
export const UPDATE_TYPESGALLON_FAIL = "UPDATE_TYPESGALLON_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
