export const CREATE_TYPESGALLON_REQUEST = "CREATE_TYPESGALLON_REQUEST";
export const CREATE_TYPESGALLON_SUCCESS = "CREATE_TYPESGALLON_SUCCESS";
export const CREATE_TYPESGALLON_FAIL = "CREATE_TYPESGALLON_FAIL";
export const CREATE_TYPESGALLON_RESET = "CREATE_TYPESGALLON_RESET";

export const ALL_TYPESGALLON_REQUEST = "ALL_TYPESGALLON_REQUEST";
export const ALL_TYPESGALLON_SUCCESS = "ALL_TYPESGALLON_SUCCESS";
export const ALL_TYPESGALLON_FAIL = "ALL_TYPESGALLON_FAIL";

export const DELETE_TYPESGALLON_REQUEST = "DELETE_TYPESGALLON_REQUEST";
export const DELETE_TYPESGALLON_SUCCESS = "DELETE_TYPESGALLON_SUCCESS";
export const DELETE_TYPESGALLON_RESET = "DELETE_TYPESGALLON_RESET";
export const DELETE_TYPESGALLON_FAIL = "DELETE_TYPESGALLON_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
