export const CREATE_WALKINPOS_REQUEST = "CREATE_WALKINPOS_REQUEST";
export const CREATE_WALKINPOS_SUCCESS = "CREATE_WALKINPOS_SUCCESS";
export const CREATE_WALKINPOS_FAIL = "CREATE_WALKINPOS_FAIL";
export const CREATE_WALKINPOS_RESET = "CREATE_WALKINPOS_RESET";

export const ALL_WALKINPOS_REQUEST = "ALL_WALKINPOS_REQUEST";
export const ALL_WALKINPOS_SUCCESS = "ALL_WALKINPOS_SUCCESS";
export const ALL_WALKINPOS_FAIL = "ALL_WALKINPOS_FAIL";
export const ALL_WALKINPOS_RESET = "ALL_WALKINPOS_RESET";

export const SINGLE_WALKINPOS_REQUEST = "SINGLE_WALKINPOS_REQUEST";
export const SINGLE_WALKINPOS_SUCCESS = "SINGLE_WALKINPOS_SUCCESS";
export const SINGLE_WALKINPOS_FAIL = "SINGLE_WALKINPOS_FAIL";
export const SINGLE_WALKINPOS_RESET = "SINGLE_WALKINPOS_RESET";

export const DELETE_WALKINPOS_REQUEST = "DELETE_WALKINPOS_REQUEST";
export const DELETE_WALKINPOS_SUCCESS = "DELETE_WALKINPOS_SUCCESS";
export const DELETE_WALKINPOS_FAIL = "DELETE_WALKINPOS_FAIL";
export const DELETE_WALKINPOS_RESET = "DELETE_WALKINPOS_RESET";

export const UPDATE_WALKINPOS_REQUEST = "UPDATE_WALKINPOS_REQUEST";
export const UPDATE_WALKINPOS_SUCCESS = "UPDATE_WALKINPOS_SUCCESS";
export const UPDATE_WALKINPOS_RESET = "UPDATE_WALKINPOS_RESET";
export const UPDATE_WALKINPOS_FAIL = "UPDATE_WALKINPOS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
